### ISSUE TITLE
Robot Font Not Working

### ISSUE THREAD

**Issue by nahtnam** [alchapone/polymer-paper-rails#7]
Hey @alchapone @lloeki!

I imported the font-roboto component, but everything on the site is still in Times New Roman.

Thanks.

**Comment by HermannHH** [comment]
Hi @nahtnam ,

I am currently trying to implement this GEM with one of my projects. I am having different issues than you are, but noticed that I am seeing an alert regarding robotto in Firebug. Perhaps check your Firebug Console to see if you're not experiencing the same. Might give the guys some more information to work with.

**Comment by nahtnam** [comment]
@HermannHH I was able to get it working by adding this CSS at the top of my page:
```
html body {
  font-family: RobotoDraft;
}
```

What issues are you having? Maybe I can help you out.

**Comment by HermannHH** [comment]
Just not getting any of the components to show in Firefox. Works perfectly in Chrome. And only shows the following in Firefox Firebug and not in Chrome:

![rsz_screenshot_from_2015-01-11_080610](https://cloud.githubusercontent.com/assets/5584878/5694868/23f401a8-9987-11e4-8e26-83a8ffedbc04.png)

**Comment by nahtnam** [comment]
Unfortunately im not sure what the issue is.

Sorry.
